config/routes.rb
require 'sidekiq/web'
require 'api/api'

Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: "/admin/sidekiq", as: :sidekiq
  end

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git.bin_path,
    project_root: Gitlab.config.gitlab_shell.repos_path,
    upload_pack:  Gitlab.config.gitlab_shell.upload_pack,
    receive_pack: Gitlab.config.gitlab_shell.receive_pack
  }), at: '/', constraints: lambda { |request| /[-\/\w\.]+\.git\//.match(request.path_info) }

  #
  # Help
  #
  get 'help'                => 'help#index'
  get 'help/api'            => 'help#api'
  get 'help/markdown'       => 'help#markdown'
  get 'help/permissions'    => 'help#permissions'
  get 'help/public_access'  => 'help#public_access'
  get 'help/raketasks'      => 'help#raketasks'
  get 'help/ssh'            => 'help#ssh'
  get 'help/system_hooks'   => 'help#system_hooks'
  get 'help/web_hooks'      => 'help#web_hooks'
  get 'help/workflow'       => 'help#workflow'

  #
  # Public namespace
  #
  namespace :public do
    resources :projects, only: [:index]
    root to: "projects#index"
  end

  #
  # Attachments serving
  #
  get 'files/:type/:id/:filename' => 'files#download', constraints: { id: /\d+/, type: /[a-z]+/, filename:  /.+/ }

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end

    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :project_update
        put :project_teams_update
        delete :remove_project
      end
    end

    resources :teams, constraints: { id: /[^\/]+/ } do
      scope module: :teams do
        resources :members,   only: [:edit, :update, :destroy, :new, :create]
        resources :projects,  only: [:edit, :update, :destroy, :new, :create], constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end

    resource :logs, only: [:show]
    resource :resque, controller: 'resque', only: [:show]

    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:index, :show] do
      scope module: :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
        resources :members, only: [:edit, :update, :destroy]
      end
    end

    root to: "dashboard#index"
  end

  get "errors/githost"

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :account
      get :history
      get :token
      get :design

      put :update_password
      put :reset_private_token
      put :update_username
    end

    resource :notifications
  end

  resources :keys
  match "/u/:username" => "users#show", as: :user, constraints: { username: /.*/ }



  #
  # Dashboard Area
  #
  resource :dashboard, controller: "dashboard" do
    member do
      get :projects
      get :issues
      get :merge_requests
    end
  end

  #
  # Groups Area
  #
  resources :groups, constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}  do
    member do
      get :issues
      get :merge_requests
      get :search
      get :people
      post :team_members
    end
  end

  #
  # Teams Area
  #
  resources :teams, constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/} do
    member do
      get :issues
      get :merge_requests
    end
    scope module: :teams do
      resources :members,   only: [:index, :new, :create, :edit, :update, :destroy]
      resources :projects,  only: [:index, :new, :create, :edit, :update, :destroy], constraints: { id: /[a-zA-Z.0-9_\-\/]+/ }
    end
  end

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations }

  #
  # Project Area
  #
  resources :projects, constraints: { id: /(?:[a-zA-Z.0-9_\-]+\/)?[a-zA-Z.0-9_\-]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      put :transfer
      post :fork
      get :autocomplete_sources
    end

    resources :blob,    only: [:show], constraints: {id: /.+/}
    resources :raw,    only: [:show], constraints: {id: /.+/}
    resources :tree,    only: [:show], constraints: {id: /.+/, format: /(html|js)/ }
    resources :edit_tree,    only: [:show, :update], constraints: {id: /.+/}, path: 'edit'
    resources :commit,  only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
    resources :commits, only: [:show], constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}
    resources :compare, only: [:index, :create]
    resources :blame,   only: [:show], constraints: {id: /.+/}
    resources :graph,   only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/}
    match "/compare/:from...:to" => "compare#show", as: "compare", via: [:get, :post], constraints: {from: /.+/, to: /.+/}

    resources :wikis, only: [:show, :edit, :destroy, :create] do
      collection do
        get :pages
        put ':id' => 'wikis#update'
        get :git_access
      end

      member do
        get "history"
      end
    end

    resource :wall, only: [:show] do
      member do
        get 'notes'
      end
    end

    resource :repository do
      member do
        get "branches"
        get "tags"
        get "stats"
        get "archive"
      end
    end

    resources :services, constraints: { id: /[^\/]+/ }, only: [:index, :edit, :update] do
      member do
        get :test
      end
    end

    resources :deploy_keys do
      member do
        put :enable
        put :disable
      end
    end

    resources :protected_branches, only: [:index, :create, :destroy]

    resources :refs, only: [] do
      collection do
        get "switch"
      end

      member do
        # tree viewer logs
        get "logs_tree", constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }
        get "logs_tree/:path" => "refs#logs_tree",
          as: :logs_file,
          constraints: {
            id:   /[a-zA-Z.0-9\/_\-]+/,
            path: /.*/
          }
      end
    end

    resources :merge_requests, constraints: {id: /\d+/}, except: [:destroy] do
      member do
        get :diffs
        get :automerge
        get :automerge_check
        get :ci_status
      end

      collection do
        get :branch_from
        get :branch_to
      end
    end

    resources :snippets do
      member do
        get "raw"
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end


    resources :team, controller: 'team_members', only: [:index]
    resources :milestones, except: [:destroy]

    resources :labels, only: [:index] do
      collection do
        post :generate
      end
    end

    resources :issues, except: [:destroy] do
      collection do
        post  :bulk_update
      end
    end

    resources :team_members, except: [:index, :edit] do
      collection do

        # Used for import team
        # from another project
        get :import
        post :apply_import
      end
    end

    scope module: :projects do
      resources :teams, only: [] do
        collection do
          get :available
          post :assign
        end
        member do
          delete :resign
        end
      end
    end

    resources :notes, only: [:index, :create, :destroy] do
      collection do
        post :preview
      end
    end
  end

  root to: "dashboard#show"
end

app/models/repository.rb
class Repository
  attr_accessor :raw_repository

  def initialize(path_with_namespace, default_branch)
    @raw_repository = Gitlab::Git::Repository.new(path_with_namespace, default_branch)
  rescue Gitlab::Git::Repository::NoRepository
    nil
  end

  def exists?
    raw_repository
  end

  def empty?
    raw_repository.empty?
  end

  def commit(id = nil)
    commit = raw_repository.commit(id)
    commit = Commit.new(commit) if commit
    commit
  end

  def commits(ref, path = nil, limit = nil, offset = nil)
    commits = raw_repository.commits(ref, path, limit, offset)
    commits = Commit.decorate(commits) if commits.present?
    commits
  end

  def commits_between(target, source)
    commits = raw_repository.commits_between(target, source)
    commits = Commit.decorate(commits) if commits.present?
    commits
  end

  def branch_names
    Rails.cache.fetch(cache_key(:branch_names)) do
      raw_repository.branch_names
    end
  end

  def tag_names
    Rails.cache.fetch(cache_key(:tag_names)) do
      raw_repository.tag_names
    end
  end

  def method_missing(m, *args, &block)
    raw_repository.send(m, *args, &block)
  end

  # Return repo size in megabytes
  # Cached in redis
  def size
    Rails.cache.fetch(cache_key(:size)) do
      raw_repository.size
    end
  end

  def expire_cache
    Rails.cache.delete(cache_key(:size))
    Rails.cache.delete(cache_key(:branch_names))
    Rails.cache.delete(cache_key(:tag_names))
  end

  def cache_key(type)
    "#{type}:#{path_with_namespace}"
  end

  def respond_to?(method)
    return true if raw_repository.respond_to?(method)

    super
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ProjectResourceController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    @activities = @repository.commits_with_refs(20)
  end

  def branches
    @branches = @repository.branches
  end

  def tags
    @tags = @repository.tags
  end

  def stats
    @stats = Gitlab::Git::Stats.new(@repository.raw, @repository.root_ref)
    @graph = @stats.graph
  end

  def archive
    unless can?(current_user, :download_code, @project)
      render_404 and return
    end


    storage_path = Rails.root.join("tmp", "repositories")

    file_path = @repository.archive_repo(params[:ref], storage_path)

    if file_path
      # Send file to user
      send_file file_path
    else
      render_404
    end
  end
end

app/views/repositories/_branch.html.haml
- commit = Commit.new(Gitlab::Git::Commit.new(branch.commit))
%tr
  %td
    = link_to project_commits_path(@project, branch.name) do
      - if @project.protected_branch? branch.name
        %i.icon-lock
      - else
        %i.icon-unlock
      %strong= truncate(branch.name, length: 60)
      - if branch.name == @repository.root_ref
        %span.label default
  %td
    = link_to project_commit_path(@project, commit.id), class: 'commit_short_id' do
      = commit.short_id
    = image_tag gravatar_icon(commit.author_email), class: "avatar s16"
    %span.light
      = gfm escape_once(truncate(commit.title, length: 40))
    %span
      = time_ago_in_words(commit.committed_date)
      ago
  %td
    - if can? current_user, :download_code, @project
      = link_to archive_project_repository_path(@project, ref: branch.name) do
        %i.icon-download-alt
        Download

app/views/repositories/_feed.html.haml
- commit = update
%tr
  %td
    = link_to project_commits_path(@project, commit.head.name) do
      %strong
        = commit.head.name
      - if @project.root_ref?(commit.head.name)
        %span.label default

  %td
    %div
      = link_to project_commits_path(@project, commit.id) do
        %code= commit.short_id
      = image_tag gravatar_icon(commit.author_email), class: "", width: 16
      = gfm escape_once(truncate(commit.title, length: 40))
  %td
    %span.pull-right.cgray
      = time_ago_in_words(commit.committed_date)
      ago

app/views/repositories/_filter.html.haml
%ul.nav.nav-pills.nav-stacked
  = nav_link(path: 'repositories#show') do
    = link_to 'Recent', project_repository_path(@project)
  = nav_link(path: 'protected_branches#index') do
    = link_to project_protected_branches_path(@project) do
      Protected
      %i.icon-lock
  = nav_link(path: 'repositories#branches') do
    = link_to 'All branches', branches_project_repository_path(@project)

app/views/repositories/branches.html.haml
= render "commits/head"
.row
  .span3
    = render "filter"
  .span9
    - unless @branches.empty?
      %table
        %thead
          %tr
            %th Name
            %th Last commit
            %th
        %tbody
          - @branches.each do |branch|
            = render "repositories/branch", branch: branch

app/views/repositories/show.html.haml
= render "commits/head"
.row
  .span3
    = render "filter"
  .span9
    %table
      %thead
        %tr
          %th Name
          %th Last commit
          %th
      - @activities.each do |update|
        = render "repositories/branch", branch: update.head

app/views/repositories/stats.html.haml
= render "commits/head"
.row
  .span6
    %div#activity-chart.chart
    %hr
    %p
      %b Total commits:
      %span= @stats.commits_count
    %p
      %b Total files in #{@repository.root_ref}:
      %span= @stats.files_count
    %p
      %b Authors:
      %span= @stats.authors_count


  .span6
    %h4 Top 50 Committers:
    %ol.styled
      - @stats.authors[0...50].each do |author|
        %li
          = image_tag gravatar_icon(author.email, 16), class: 'avatar s16'
          = author.name
          %small.light= author.email
          .pull-right
            = author.commits


:javascript
  var labels = [#{@graph.labels.to_json}];
  var commits = [#{@graph.commits.join(', ')}];
  var title = "Commit activity for last #{@graph.weeks} weeks";
  Chart.init(labels, commits, title);

app/views/repositories/tags.html.haml
= render "commits/head"
- unless @tags.empty?
  %ul.bordered-list
    - @tags.each do |tag|
      - commit = Commit.new(Gitlab::Git::Commit.new(tag.commit))
      %li
        %h5
          = link_to project_commits_path(@project, tag.name), class: "" do
            %i.icon-tag
            = tag.name
          %small
            = truncate(tag.message || '', length: 70)
          .pull-right
            %span.light
              = time_ago_in_words(commit.committed_date)
              ago
        %div.prepend-left-20
          = link_to commit.short_id(8), project_commit_path(@project, commit), class: "monospace"
          &ndash;
          = link_to_gfm truncate(commit.title, length: 70), project_commit_path(@project, commit.id), class: "cdark"

          - if can? current_user, :download_code, @project
            .pull-right
              = link_to archive_project_repository_path(@project, ref: tag.name) do
                %i.icon-download-alt
                Download


- else
  %h3.nothing_here_message
    Repository has no tags yet.
    %br
    %small
      Use git tag command to add a new one:
      %br
      %span.monospace git tag -a v1.4 -m 'version 1.4'