config/routes.rb
require 'sidekiq/web'
require 'api/api'

Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: "/admin/sidekiq", as: :sidekiq
  end

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git.bin_path,
    project_root: Gitlab.config.gitlab_shell.repos_path,
    upload_pack:  Gitlab.config.gitlab_shell.upload_pack,
    receive_pack: Gitlab.config.gitlab_shell.receive_pack
  }), at: '/', constraints: lambda { |request| /[-\/\w\.]+\.git\//.match(request.path_info) }

  #
  # Help
  #
  get 'help'                => 'help#index'
  get 'help/api'            => 'help#api'
  get 'help/markdown'       => 'help#markdown'
  get 'help/permissions'    => 'help#permissions'
  get 'help/public_access'  => 'help#public_access'
  get 'help/raketasks'      => 'help#raketasks'
  get 'help/ssh'            => 'help#ssh'
  get 'help/system_hooks'   => 'help#system_hooks'
  get 'help/web_hooks'      => 'help#web_hooks'
  get 'help/workflow'       => 'help#workflow'

  #
  # Public namespace
  #
  namespace :public do
    resources :projects, only: [:index]
    root to: "projects#index"
  end

  #
  # Attachments serving
  #
  get 'files/:type/:id/:filename' => 'files#download', constraints: { id: /\d+/, type: /[a-z]+/, filename:  /.+/ }

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end

    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :project_update
        put :project_teams_update
        delete :remove_project
      end
    end

    resources :teams, constraints: { id: /[^\/]+/ } do
      scope module: :teams do
        resources :members,   only: [:edit, :update, :destroy, :new, :create]
        resources :projects,  only: [:edit, :update, :destroy, :new, :create], constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end

    resource :logs, only: [:show]
    resource :resque, controller: 'resque', only: [:show]

    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:index, :show] do
      scope module: :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
        resources :members, only: [:edit, :update, :destroy]
      end
    end

    root to: "dashboard#index"
  end

  get "errors/githost"

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :account
      get :history
      get :token
      get :design

      put :update_password
      put :reset_private_token
      put :update_username
    end

    resource :notifications
  end

  resources :keys
  match "/u/:username" => "users#show", as: :user, constraints: { username: /.*/ }



  #
  # Dashboard Area
  #
  resource :dashboard, controller: "dashboard" do
    member do
      get :projects
      get :issues
      get :merge_requests
    end
  end

  #
  # Groups Area
  #
  resources :groups, constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}  do
    member do
      get :issues
      get :merge_requests
      get :search
      get :people
      post :team_members
    end
  end

  #
  # Teams Area
  #
  resources :teams, constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/} do
    member do
      get :issues
      get :merge_requests
    end
    scope module: :teams do
      resources :members,   only: [:index, :new, :create, :edit, :update, :destroy]
      resources :projects,  only: [:index, :new, :create, :edit, :update, :destroy], constraints: { id: /[a-zA-Z.0-9_\-\/]+/ }
    end
  end

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations }

  #
  # Project Area
  #
  resources :projects, constraints: { id: /(?:[a-zA-Z.0-9_\-]+\/)?[a-zA-Z.0-9_\-]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      put :transfer
      post :fork
      get :autocomplete_sources
    end

    resources :blob,    only: [:show], constraints: {id: /.+/}
    resources :raw,    only: [:show], constraints: {id: /.+/}
    resources :tree,    only: [:show], constraints: {id: /.+/, format: /(html|js)/ }
    resources :edit_tree,    only: [:show, :update], constraints: {id: /.+/}, path: 'edit'
    resources :commit,  only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
    resources :commits, only: [:show], constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}
    resources :compare, only: [:index, :create]
    resources :blame,   only: [:show], constraints: {id: /.+/}
    resources :graph,   only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/}
    match "/compare/:from...:to" => "compare#show", as: "compare", via: [:get, :post], constraints: {from: /.+/, to: /.+/}

    resources :wikis, only: [:show, :edit, :destroy, :create] do
      collection do
        get :pages
        put ':id' => 'wikis#update'
        get :git_access
      end

      member do
        get "history"
      end
    end

    resource :wall, only: [:show] do
      member do
        get 'notes'
      end
    end

    resource :repository do
      member do
        get "branches"
        get "tags"
        get "stats"
        get "archive"
      end
    end

    resources :services, constraints: { id: /[^\/]+/ }, only: [:index, :edit, :update] do
      member do
        get :test
      end
    end

    resources :deploy_keys do
      member do
        put :enable
        put :disable
      end
    end

    resources :protected_branches, only: [:index, :create, :destroy]

    resources :refs, only: [] do
      collection do
        get "switch"
      end

      member do
        # tree viewer logs
        get "logs_tree", constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }
        get "logs_tree/:path" => "refs#logs_tree",
          as: :logs_file,
          constraints: {
            id:   /[a-zA-Z.0-9\/_\-]+/,
            path: /.*/
          }
      end
    end

    resources :merge_requests, constraints: {id: /\d+/}, except: [:destroy] do
      member do
        get :diffs
        get :automerge
        get :automerge_check
        get :ci_status
      end

      collection do
        get :branch_from
        get :branch_to
      end
    end

    resources :snippets do
      member do
        get "raw"
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end


    resources :team, controller: 'team_members', only: [:index]
    resources :milestones, except: [:destroy]

    resources :labels, only: [:index] do
      collection do
        post :generate
      end
    end

    resources :issues, except: [:destroy] do
      collection do
        post  :bulk_update
      end
    end

    resources :team_members, except: [:index, :edit] do
      collection do

        # Used for import team
        # from another project
        get :import
        post :apply_import
      end
    end

    scope module: :projects do
      resources :teams, only: [] do
        collection do
          get :available
          post :assign
        end
        member do
          delete :resign
        end
      end
    end

    resources :notes, only: [:index, :create, :destroy] do
      collection do
        post :preview
      end
    end
  end

  root to: "dashboard#show"
end

app/controllers/admin/projects/application_controller.rb
# Provides a base class for Admin controllers to subclass
#
# Automatically sets the layout and ensures an administrator is logged in
class Admin::Projects::ApplicationController < Admin::ApplicationController

  protected

  def project
    @project ||= Project.find_with_namespace(params[:project_id])
  end
end

app/controllers/admin/projects/members_controller.rb
class Admin::Projects::MembersController < Admin::Projects::ApplicationController
  def edit
    @member = team_member
    @project = project
    @team_member_relation = team_member_relation
  end

  def update
    if team_member_relation.update_attributes(params[:team_member])
      redirect_to [:admin, project],  notice: 'Project Access was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    team_member_relation.destroy

    redirect_to :back
  end

  private

  def team_member
    @member ||= project.users.find_by_username(params[:id])
  end

  def team_member_relation
    team_member.users_projects.find_by_project_id(project)
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  before_filter :project, only: [:edit, :show, :update, :destroy, :team_update]

  def index
    @projects = Project.scoped
    @projects = @projects.where(namespace_id: params[:namespace_id]) if params[:namespace_id].present?
    @projects = @projects.where(public: true) if params[:public_only].present?
    @projects = @projects.with_push if params[:with_push].present?
    @projects = @projects.abandoned if params[:abandoned].present?
    @projects = @projects.where(namespace_id: nil) if params[:namespace_id] == Namespace.global_id
    @projects = @projects.search(params[:name]) if params[:name].present?
    @projects = @projects.includes(:namespace).order("namespaces.path, projects.name ASC").page(params[:page]).per(20)
  end

  def show
    @repository = @project.repository
    @users = User.active
    @users = @users.not_in_project(@project) if @project.users.present?
    @users = @users.all
  end

  protected

  def project
    id = params[:project_id] || params[:id]

    @project = Project.find_with_namespace(id)
    @project || render_404
  end
end

app/controllers/admin/teams/projects_controller.rb
class Admin::Teams::ProjectsController < Admin::Teams::ApplicationController
  def new
    @projects = Project.scoped
    @projects = @projects.without_team(user_team) if user_team.projects.any?
    #@projects.reject!(&:empty_repo?)
  end

  def create
    unless params[:project_ids].blank?
      project_ids = params[:project_ids]
      access = params[:greatest_project_access]
      user_team.assign_to_projects(project_ids, access)
    end

    redirect_to admin_team_path(user_team), notice: 'Team of users was successfully assgned to projects.'
  end

  def edit
    team_project
  end

  def update
    if user_team.update_project_access(team_project, params[:greatest_project_access])
      redirect_to admin_team_path(user_team), notice: 'Access was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    user_team.resign_from_project(team_project)
    redirect_to admin_team_path(user_team), notice: 'Team of users was successfully reassigned from project.'
  end

  protected

  def team_project
    @project ||= user_team.projects.find_with_namespace(params[:id])
  end

end

app/controllers/projects/application_controller.rb
class Projects::ApplicationController < ApplicationController

  before_filter :authorize_admin_team_member!

  protected

  def user_team
    @team ||= UserTeam.find_by_path(params[:id])
  end

end

app/controllers/projects/teams_controller.rb
class Projects::TeamsController < Projects::ApplicationController

  def available
    @teams = current_user.is_admin? ? UserTeam.scoped : current_user.user_teams
    @teams = @teams.without_project(project)
    unless @teams.any?
      redirect_to project_team_index_path(project), notice: "No available teams for assigment."
    end
  end

  def assign
    unless params[:team_id].blank?
      team = UserTeam.find(params[:team_id])
      access = params[:greatest_project_access]
      team.assign_to_project(project, access)
    end
    redirect_to project_team_index_path(project)
  end

  def resign
    team = project.user_teams.find_by_path(params[:id])
    team.resign_from_project(project)

    redirect_to project_team_index_path(project)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ProjectResourceController
  skip_before_filter :project, only: [:new, :create]
  skip_before_filter :repository, only: [:new, :create]

  # Authorize
  before_filter :authorize_read_project!, except: [:index, :new, :create]
  before_filter :authorize_admin_project!, only: [:edit, :update, :destroy, :transfer]
  before_filter :require_non_empty_project, only: [:blob, :tree, :graph]

  layout 'application', only: [:new, :create]

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = ::Projects::CreateContext.new(current_user, params[:project]).execute

    respond_to do |format|
      flash[:notice] = 'Project was successfully created.' if @project.saved?
      format.html do
        if @project.saved?
          redirect_to @project
        else
          render action: "new"
        end
      end
      format.js
    end
  end

  def update
    status = ::Projects::UpdateContext.new(project, current_user, params).execute

    respond_to do |format|
      if status
        flash[:notice] = 'Project was successfully updated.'
        format.html { redirect_to edit_project_path(project), notice: 'Project was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js
      end
    end
  end

  def transfer
    ::Projects::TransferContext.new(project, current_user, params).execute
  end

  def show
    limit = (params[:limit] || 20).to_i
    @events = @project.events.recent.limit(limit).offset(params[:offset] || 0)

    respond_to do |format|
      format.html do
        if @project.empty_repo?
          render "projects/empty"
        else
          @last_push = current_user.recent_push(@project.id)
          render :show
        end
      end
      format.js
    end
  end

  def destroy
    return access_denied! unless can?(current_user, :remove_project, project)

    project.team.truncate
    project.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
    end
  end

  def fork
    @project = ::Projects::ForkContext.new(project, current_user).execute

    respond_to do |format|
      format.html do
        if @project.saved? && @project.forked?
          redirect_to(@project, notice: 'Project was successfully forked.')
        else
          render action: "new"
        end
      end
      format.js
    end
  end

  def autocomplete_sources
    @suggestions = {
      emojis: Emoji.names,
      issues: @project.issues.select([:id, :title, :description]),
      members: @project.users.select([:username, :name]).order(:username)
    }

    respond_to do |format|
      format.json { render :json => @suggestions }
    end
  end
end

app/controllers/teams/projects_controller.rb
class Teams::ProjectsController < Teams::ApplicationController
  def create
    redirect_to :back if params[:project_ids].blank?

    project_ids = params[:project_ids]
    access = params[:greatest_project_access]

    # Reject non-allowed projects
    allowed_project_ids = current_user.owned_projects.map(&:id)
    project_ids.select! { |id| allowed_project_ids.include?(id.to_i) }

    # Assign projects to team
    user_team.assign_to_projects(project_ids, access)

    redirect_to edit_team_path(user_team), notice: 'Team of users was successfully assigned to projects.'
  end

  def edit
    team_project
  end

  def update
    if user_team.update_project_access(team_project, params[:greatest_project_access])
      redirect_to edit_team_path(user_team), notice: 'Access was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    user_team.resign_from_project(team_project)
    redirect_to team_projects_path(user_team), notice: 'Team of users was successfully reassigned from project.'
  end

  private

  def team_project
    @project ||= user_team.projects.find_with_namespace(params[:id])
  end
end

app/helpers/admin/teams/projects_helper.rb
module Admin::Teams::ProjectsHelper
  def assigned_since(team, project)
    team.user_team_project_relationships.find_by_project_id(project).created_at
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def remove_from_project_team_message(project, user)
    "You are going to remove #{user.name} from #{project.name} project team. Are you sure?"
  end

  def link_to_project project
    link_to project do
      title = content_tag(:strong, project.name)

      if project.namespace
        namespace = content_tag(:span, "#{project.namespace.human_name} / ", class: 'tiny')
        title = namespace + title
      end

      title
    end
  end

  def link_to_member(project, author, opts = {})
    default_opts = { avatar: true }
    opts = default_opts.merge(opts)

    return "(deleted)" unless author

    author_html =  ""

    # Build avatar image tag
    author_html << image_tag(gravatar_icon(author.try(:email)), width: 16, class: "avatar avatar-inline s16") if opts[:avatar]

    # Build name span tag
    author_html << content_tag(:span, sanitize(author.name), class: 'author')

    author_html = author_html.html_safe

    link_to(author_html, user_path(author), class: "author_link").html_safe
  end

  def project_title project
    if project.group
      content_tag :span do
        link_to(simple_sanitize(project.group.name), group_path(project.group)) + " / " + project.name
      end
    else
      project.name
    end
  end
end

app/views/admin/projects/index.html.haml
%h3.page_title
  Projects
  = link_to 'New Project', new_project_path, class: "btn btn-small pull-right"

%hr

.row
  .span4
    .admin-filter
      = form_tag admin_projects_path, method: :get, class: 'form-inline' do
        .control-group
          = label_tag :name, 'Name:', class: 'control-label'
          .controls
            = text_field_tag :name, params[:name], class: "span2"

        .control-group
          = label_tag :namespace_id, 'Namespace:', class: 'control-label'
          .controls
            = select_tag :namespace_id, namespaces_options(params[:namespace_id], :all), class: "chosen span2", prompt: "Any"
        .control-group
          = label_tag :public_only, 'Public Only', class: 'control-label'
          .controls
            = check_box_tag :public_only, 1, params[:public_only]
        .control-group
          = label_tag :with_push, 'Not empty', class: 'control-label'
          .controls
            = check_box_tag :with_push, 1, params[:with_push]
            &nbsp;
            %span.light Projects with push events
        .control-group
          = label_tag :abandoned, 'Abandoned', class: 'control-label'
          .controls
            = check_box_tag :abandoned, 1, params[:abandoned]
            &nbsp;
            %span.light No activity over 6 month



        .form-actions
          = submit_tag "Search", class: "btn submit btn-primary"
          = link_to "Reset", admin_projects_path, class: "btn"
  .span8
    .ui-box
      %h5.title
        Projects (#{@projects.total_count})
      %ul.well-list
        - @projects.each do |project|
          %li
            - if project.public
              %i.icon-share
            - else
              %i.icon-lock.cgreen
            = link_to project.name_with_namespace, [:admin, project]
            .pull-right
              = link_to 'Edit', edit_project_path(project), id: "edit_#{dom_id(project)}", class: "btn btn-small"
              = link_to 'Destroy', [project], confirm: "REMOVE #{project.name}? Are you sure?", method: :delete, class: "btn btn-small btn-remove"
        - if @projects.blank?
          %p.nothing_here_message 0 projects matches
    = paginate @projects, theme: "gitlab"

app/views/admin/projects/show.html.haml
%h3.page_title
  Project: #{@project.name_with_namespace}
  = link_to edit_project_path(@project), class: "btn pull-right" do
    %i.icon-edit
    Edit
%hr
.row
  .span6
    .ui-box
      %h5.title
        Project info:
      %ul.well-list
        %li
          %span.light Name:
          %strong= @project.name
        %li
          %span.light Namespace:
          %strong
            - if @project.namespace
              = link_to @project.namespace.human_name, [:admin, @project.group || @project.owner]
            - else
              Global
        %li
          %span.light Owned by:
          %strong
            - if @project.owner
              = link_to @project.owner_name, admin_user_path(@project.owner)
            - else
              (deleted)

        %li
          %span.light Created by:
          %strong
            = @project.creator.try(:name) || '(deleted)'

        %li
          %span.light Created at:
          %strong
            = @project.created_at.stamp("March 1, 1999")

        %li
          %span.light http:
          %strong
            = link_to @project.http_url_to_repo
        %li
          %span.light ssh:
          %strong
            = link_to @project.ssh_url_to_repo
        - if @project.repository.exists?
          %li
            %span.light fs:
            %strong
              = @repository.path_to_repo

          %li
            %span.light last commit:
            %strong
              = last_commit(@project)
        - else
          %li
            %span.light repository:
            %strong.cred
              does not exist

        %li
          %span.light access:
          %strong
            - if @project.public
              %span.cblue
                %i.icon-share
                Public
            - else
              %span.cgreen
                %i.icon-lock
                Private
  .span6
    .ui-box
      %h5.title
        Team
        %small
          (#{@project.users.count})
        = link_to project_team_index_path(@project), class: "btn btn-tiny" do
          %i.icon-edit
          Edit Team
      %ul.well-list.team_members
        - @project.users.each do |tm|
          %li
            %strong
              = link_to tm.name, admin_user_path(tm)
            %span.pull-right.light= @project.project_access_human(tm)